apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: tmate
  labels:
    app: tmate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tmate
  template:
    metadata:
      labels:
        app: tmate
    spec:
      containers:
      - name: tmate
        image: tmate/tmate-ssh-server
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: SSH_KEYS_PATH
          value: "/etc/tmate/keys"
        - name: SSH_HOSTNAME
          value: "tmate-ssh-server"
        - name: SSH_PORT_LISTEN
          value: "2222"
        volumeMounts:
        - name: tmate-keys
          mountPath: "/etc/tmate/keys"
          readOnly: true
      volumes:
      - name: tmate-keys
        secret:
          secretName: tmate-keys
